#!/usr/bin/env python
# PROFILES STREAMER
# The streamer is listening to a list of accounts, stored in the userID.txt file which is generated by the twythonize_list.py script; Using tweepy module to authenticate with Twitter and stream tweets; Using pickle module to read and write the list of userIDs;

#Import the necessary methods from tweepy library
from tweepy.streaming import StreamListener
from tweepy import OAuthHandler
from tweepy import Stream
from auth import TwitterAuthProfiles
import pickle

"""
----------------
P R O F I L E S
----------------
"""

# read the list of userIDs from a file
with open("userID.txt", 'rb') as f:
    userID_list = pickle.load(f)

"""
----------------
S T R E A M E R
----------------
"""

#This is a basic listener that just prints received tweets to stdout.
class StdOutListener(StreamListener):

    def on_data(self, data):
        #print data
        with open('profile_tweets.json','a') as tf:
            tf.write(data)
        return True

    def on_error(self, status):
        print status

"""
----------------
T H E   L O O P
----------------
"""

try:
    while True:
        if __name__ == '__main__':
            #This handles Twitter authetification and the connection to Twitter Streaming API
            l = StdOutListener()
            auth = OAuthHandler(TwitterAuthProfiles.consumer_key, TwitterAuthProfiles.consumer_secret)
            auth.set_access_token(TwitterAuthProfiles.access_token, TwitterAuthProfiles.access_token_secret)
            stream = Stream(auth, l)

            #This line filter Twitter Streams to capture data by the keywords: 'architecture' etc.
            stream.filter(follow=userID_list)

except KeyboardInterrupt:
    pass
